POST http://localhost:8000/
Content-Type: application/json

{"user":"60fc0668f29c8b58d45a11a0","name":"Amazon Echo Dot 3rd Generation","image":"/images/alexa.jpg","description":"Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space","brand":"Amazon","category":"Electronics","price":29.99,"countInStock":0,"rating":4,"numReviews":12}